name: Caller Workflow 

on:
  workflow_dispatch:

jobs:
  reusable-1:
    uses: ./.github/workflows/reusable-workflow.yaml
    with:
      node-version: "20"
      run-tests: true
  reusable-2:
    uses: ./.github/workflows/reusable-workflow-2.yaml
    with:
      node-version: "24"
      run-tests: false
